name: CI - Lint, Format, Docker Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: 'pip' # Cache pip dependencies

      - name: Install dependencies for linting
        run: pip install -r requirements.txt ruff black

      - name: Run Ruff Linter
        run: ruff check . --output-format=github

      - name: Run Black Formatter Check
        run: black --check .

  docker-build-check:
    name: Docker Image Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # Only build, do not push to a registry
          tags: pyschlage-api:latest-ci # A temporary tag for the build
          # No --env-file here, as secrets are not needed for a build check